/*
DROP TABLE TIPO_INGRESSO;
DROP TABLE INGRESSO;
DROP TABLE ATRACAO;
DROP TABLE COMPRA;
DROP TABLE CLIENTE;
DROP TABLE COMPETE;
DROP TABLE ATLETA;
DROP TABLE TIPOPESSOA;
DROP TABLE PESSOA;
DROP TABLE DISPUTAMODALIDADE;
DROP TABLE CATEGORIAA;
DROP TABLE JOGA;
DROP TABLE DISPUTA;
DROP TABLE PERTENCEGRUPO;
DROP TABLE GRUPO;
DROP TABLE UNIPARTEVENTO;
DROP TABLE CATEGORIAB;
DROP TABLE JOGO;
DROP TABLE EVENTO;
DROP TABLE MODALIDADE;
DROP TABLE UNIVERSIDADE;
DROP TABLE LOCAL;*/

CREATE TABLE LOCAL (
      NOMEDOLOCAL VARCHAR(100) NOT NULL PRIMARY KEY,
      LOGRADOURO VARCHAR(100) NOT NULL,
      NUMERO INTEGER NOT NULL,
      BAIRRO VARCHAR(50) NOT NULL,
      CEP VARCHAR(10) NOT NULL,
      CIDADE VARCHAR(50) NOT NULL
);

CREATE TABLE UNIVERSIDADE (
      COD_UNIVERSIDADE INTEGER NOT NULL PRIMARY KEY, 
      NOME VARCHAR(100) NOT NULL,
      CIDADE VARCHAR(50) NOT NULL,
      ESTADO VARCHAR(2) NOT NULL,
      LOGOTIPO VARCHAR(512) NOT NULL,
      GRITO_DE_GUERRA  VARCHAR(512) NOT NULL
      -- todo: especificar possiveis valores de estados
);

CREATE TABLE MODALIDADE (
      MODALIDADE VARCHAR(50) NOT NULL PRIMARY KEY,
      CATEGORIA CHAR NOT NULL
);

CREATE TABLE EVENTO (
      COD_EVENTO INTEGER PRIMARY KEY,
      NOMEEVENTO VARCHAR(50) NOT NULL,
      DESCRICAOEVENTO VARCHAR(512) NOT NULL,
      LOGOTIPO VARCHAR(512) NOT NULL
);

CREATE TABLE JOGO (
      ID_JOGO INTEGER NOT NULL,
      DATA DATE NOT NULL,
      HORARIO VARCHAR2(8) NOT NULL,
      EVENTO INTEGER NOT NULL,
      MODALIDADE VARCHAR(50) NOT NULL,
      PLACAR INTEGER NOT NULL,
      LOCAL VARCHAR(50) NOT NULL,
       PRIMARY KEY(ID_JOGO, DATA, HORARIO, EVENTO, MODALIDADE),
       FOREIGN KEY (MODALIDADE) REFERENCES MODALIDADE (MODALIDADE),
       FOREIGN KEY (EVENTO) REFERENCES EVENTO(COD_EVENTO)
);

CREATE TABLE CATEGORIAB(
      MODALIDADE VARCHAR(50) NOT NULL PRIMARY KEY,
      FOREIGN KEY (MODALIDADE) REFERENCES MODALIDADE (MODALIDADE)
);

CREATE TABLE UNIPARTEVENTO(
      EVENTO INTEGER NOT NULL,
      UNIVERSIDADE INTEGER NOT NULL,
      CLASSIFICACAO INTEGER NOT NULL,
      CONSTRAINT PK_UNIPARTEVENTO PRIMARY KEY(EVENTO, UNIVERSIDADE),
      FOREIGN KEY (EVENTO) REFERENCES EVENTO(COD_EVENTO),
      FOREIGN KEY (UNIVERSIDADE) REFERENCES UNIVERSIDADE(COD_UNIVERSIDADE)
);

CREATE TABLE GRUPO(
      IDGRUPO INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE PERTENCEGRUPO(
      UNIVERSIDADE INTEGER NOT NULL,
      ID_JOGO INTEGER NOT NULL,
      DATA DATE NOT NULL,
      HORARIO VARCHAR2(8) NOT NULL,
      EVENTO INTEGER NOT NULL,
      MODALIDADE VARCHAR(50) NOT NULL,
      GRUPO INTEGER NOT NULL PRIMARY KEY,
       FOREIGN KEY (UNIVERSIDADE) REFERENCES UNIVERSIDADE(COD_UNIVERSIDADE),
       FOREIGN KEY (ID_JOGO, DATA,HORARIO,EVENTO, MODALIDADE) REFERENCES JOGO( ID_JOGO, DATA,HORARIO,EVENTO,MODALIDADE),
       FOREIGN KEY (GRUPO) REFERENCES GRUPO(IDGRUPO)
);


CREATE TABLE DISPUTA (
      UNIVERSIDADEUM INTEGER NOT NULL,
      UNIVERSIDADEDOIS INTEGER NOT NULL,
      ID_JOGO INTEGER NOT NULL,
      DATA DATE NOT NULL,
      HORARIO VARCHAR2(8) NOT NULL,
      EVENTO INTEGER NOT NULL,
      MODALIDADE VARCHAR(50) NOT NULL,
      CONSTRAINT PK_DISPUTA PRIMARY KEY(UNIVERSIDADEUM, UNIVERSIDADEDOIS),
       FOREIGN KEY (UNIVERSIDADEUM) REFERENCES UNIVERSIDADE(COD_UNIVERSIDADE),
       FOREIGN KEY (UNIVERSIDADEDOIS) REFERENCES UNIVERSIDADE(COD_UNIVERSIDADE),
       FOREIGN KEY (ID_JOGO, DATA,HORARIO,EVENTO,MODALIDADE) REFERENCES JOGO(ID_JOGO, DATA,HORARIO,EVENTO,MODALIDADE)
);

CREATE TABLE JOGA (
      EVENTO INTEGER NOT NULL,
      MODALIDADE VARCHAR(50) NOT NULL,
      CONSTRAINT PK_JOGA PRIMARY KEY(EVENTO, MODALIDADE),
       FOREIGN KEY (MODALIDADE) REFERENCES MODALIDADE (MODALIDADE),
      FOREIGN KEY (EVENTO) REFERENCES EVENTO(COD_EVENTO)
);

CREATE TABLE CATEGORIAA (
      MODALIDADE VARCHAR(50) NOT NULL PRIMARY KEY,
       FOREIGN KEY (MODALIDADE) REFERENCES MODALIDADE (MODALIDADE)
);

CREATE TABLE DISPUTAMODALIDADE (
      UNIVERSIDADE INTEGER NOT NULL,
      MODALIDADE VARCHAR(50) NOT NULL,
      OURO INTEGER NULL,
      PRATA INTEGER NULL,
      BRONZE INTEGER NULL,
      CONSTRAINT PK_DISPUTAMODALIDADE PRIMARY KEY(UNIVERSIDADE, MODALIDADE),
      FOREIGN KEY (MODALIDADE) REFERENCES MODALIDADE (MODALIDADE)
);

CREATE TABLE PESSOA (
      CPF VARCHAR2(14) NOT NULL PRIMARY KEY,
      NOME_PESSOA VARCHAR2(50) NOT NULL,
      RG VARCHAR2(12) NOT NULL,
      SEXO CHAR NOT NULL,
      DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE TIPOPESSOA (
      CPF VARCHAR2(14) NOT NULL PRIMARY KEY,
      TIPO_PESSOA VARCHAR2(50) NOT NULL,
      FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) 
);

CREATE TABLE ATLETA (
      CPF VARCHAR2(14) NOT NULL PRIMARY KEY,
      ALTURA FLOAT NOT NULL,
      PESO FLOAT NOT NULL,
      UNIVERSIDADE INTEGER NOT NULL,
      FOREIGN KEY (CPF) REFERENCES PESSOA(CPF),
      FOREIGN KEY (UNIVERSIDADE) REFERENCES UNIVERSIDADE(COD_UNIVERSIDADE)
);

CREATE TABLE COMPETE (
      ATLETA VARCHAR2(14) NOT NULL,
      MODALIDADE VARCHAR(50) NOT NULL,
      TEMPO VARCHAR(4) NOT NULL,
      CONSTRAINT PK_COMPETE PRIMARY KEY(ATLETA, MODALIDADE),
       FOREIGN KEY (ATLETA) REFERENCES ATLETA(CPF),
       FOREIGN KEY (MODALIDADE) REFERENCES MODALIDADE (MODALIDADE)
);

CREATE TABLE CLIENTE (
      CPF VARCHAR2(14) NOT NULL PRIMARY KEY,
      TELEFONE VARCHAR2(14) NOT NULL,
      CIDADE VARCHAR2(50) NOT NULL,
      ESTADO VARCHAR2(2) NOT NULL,
      LOGRADOURO VARCHAR2(100) NOT NULL,
      NUMERO INTEGER NOT NULL,
      CEP VARCHAR2(9) NOT NULL,
      BAIRRO VARCHAR2(50) NOT NULL,
      SENHA VARCHAR2(10) NOT NULL,
      EMAIL VARCHAR2(50) NOT NULL,
      FOREIGN KEY (CPF) REFERENCES PESSOA(CPF) 
);

CREATE TABLE COMPRA (
      CLIENTE VARCHAR2(14) NOT NULL,
      DATA DATE NOT NULL,
      HORARIO VARCHAR2(8) NOT NULL,
      VALOR_TOTAL FLOAT NOT NULL,
      DATA_VENCIMENTO_BOLETO DATE,
      DATA_VALIDADE_CARTAO DATE,
      ULTIMOS_DIGITOS INTEGER,
      BANDEIRA VARCHAR2(30),
      PRIMARY KEY (CLIENTE, DATA, HORARIO),
      FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(CPF) 
);

CREATE TABLE ATRACAO (
      COD_ATRACAO INTEGER NOT NULL PRIMARY KEY,
      LOCAL_ATRACAO VARCHAR2(100),
      EVENTO INTEGER,
      DESCRICAO VARCHAR2(512) NOT NULL,
      DATA DATE,
      HORARIO VARCHAR2(8),
      CLASSIFICACAO INTEGER NOT NULL,
      E_GRATUITO INTEGER NOT NULL,
      FOREIGN KEY (LOCAL_ATRACAO) REFERENCES LOCAL(NOMEDOLOCAL),
      FOREIGN KEY (EVENTO) REFERENCES EVENTO(COD_EVENTO)
);

CREATE TABLE INGRESSO (
      COD_INGRESSO INTEGER NOT NULL PRIMARY KEY,
      ATRACAO INTEGER NOT NULL,
      CLIENTE VARCHAR2(14),
      DATA DATE,
      HORARIO VARCHAR2(8),
      FOREIGN KEY (ATRACAO) REFERENCES ATRACAO(COD_ATRACAO),
      FOREIGN KEY (CLIENTE, DATA, HORARIO) REFERENCES COMPRA(CLIENTE, DATA, HORARIO)
);

CREATE TABLE TIPO_INGRESSO (
      COD_INGRESSO INTEGER NOT NULL,
      VALOR FLOAT NOT NULL,
      NOME_TIPO_INGRESSO VARCHAR2(20) NOT NULL,
      PRIMARY KEY (COD_INGRESSO, VALOR),
      FOREIGN KEY (COD_INGRESSO) REFERENCES INGRESSO(COD_INGRESSO) 
);


COMMIT;

